### ISSUE TITLE
Defect

### ISSUE THREAD

**Issue by gunjan07** [ndlongez/cm_ca#3]
Reset the values to null for “Show Total Cash Held” and “Press to Collect Cash” when the Maintainer successfully pushes “Press Here When Finished”.

**Comment by Keerti07** [comment]
Impact of change for defect : The simulation currently does not clear the values on completion of maintenance session i.e., data not reset after session.Hence there is impact on maintenance model specifically  the maintenance controller is been affected .Also corresponding changes to be made in design model report.

**Comment by enthirant** [comment]
Resolved the defect by resetting the values to null for "Show Total Cash Held" and "Press to Collect Cash" when Maintainer pushes "Press Here When finished"

Defect is fixed

**Comment by dingyidy123** [comment]
Test Result：
After completing the session, the data of the previous session are all reset to null successfully.

Test is passed.

**Comment by prasanshettyindia** [comment]
Validation Results :  Defect has been fixed

**Comment by gunjan07** [comment]
Release as R1.0.8.1

**Comment by ndlongez** [comment]
Reviewed and close.
